version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${DB_DATABASE:-ecommerce}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
